language: android
android:
  components:

    # The BuildTools version
    - build-tools-21.1.2

    # The SDK version used to compile
    - android-21

    # Use extra android repo locations to find the appcompat-v7:21.0.0 support library
    - extra

# Specify the build script to run.
script: "./travis/build.sh"
